### Categorize Client
POST {{base_url}}/clients/{{client_id}}/categorize
Content-Type: application/json

{
  "category": "Category Name",
  "tags": [
    "PROSPECT"
  ]
}

### Set Client Status
PUT {{base_url}}/clients/{{client_id}}/set-status
Content-Type: application/json

{
  "status": "Active"
}

### Retrieve Clients Associated with Agent
GET {{base_url}}/clients/agent/{{agent_id}}
Content-Type: application/json

### View Assigned Stages for Client
GET {{base_url}}/clients/{{client_id}}/assigned-stages
Content-Type: application/json

### Complete Stage for Client
POST {{base_url}}/clients/{{client_id}}/complete-stage/{{stage_id}}
Content-Type: application/json


### View Task Details for Client
GET {{base_url}}/clients/{{client_id}}/task-details
Content-Type: application/json

### View Client Categories
GET {{base_url}}/clients/{{client_id}}/categories
Content-Type: application/json


### View Client Associated Agent
GET {{base_url}}/clients/{{client_id}}/associated-agent
Content-Type: application/json
