### get all teams
GET {{base_url}}/teams/
Accept: application/json

### get all team (location)
GET {{base_url}}/teams/all-location

### create team (partial)
POST {{base_url}}/teams/
Content-Type: application/json

{
  "title": "TEAM ONE",
  "budget": 20.0
}

> {%
    client.global.set("team_id", response.body.data.id)
%}

### get team by id
GET {{base_url}}/teams/{{team_id}}
Content-Type: application/json

### set team location
PUT {{base_url}}/teams/{{team_id}}/set-location
Accept: application/json
Content-Type: application/json

{
  "longitude": "123.456",
  "latitude": "78.901",
  "title": "Sample Location",
  "type": "City",
  "timezone": "UTC+02:00"
}


### set team budget
PUT {{base_url}}/teams/{{team_id}}/set-budget?budget=1200.0
Accept: application/json

### set team task
PUT {{base_url}}/teams/{{team_id}}/set-task/{{task_id}}
Accept: application/json

### set team manager
PUT {{base_url}}/teams/{{team_id}}/set-task/{{manager_id}}
Accept: application/json

### get agents in team
GET {{base_url}}/teams/{{team_id}}/agents
Accept: application/json

### get team performance
GET {{base_url}}/teams/{{team_id}}/performance
Accept: application/json

### get team count


